baseURL: /
languageCode: en-us
title: Thiccbois - DevOp empowerment through automation
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Develop. Communicate. Deploy.
    # Hero subtitle (optional)
    subtitle: Take stumbling teams to warp-speed
    # Button text
    buttontext: Contact Us
    # Where the main hero button links to
    buttonlink: "#get-in-touch"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork

  main_navigation:
    sections:
    - title: What we do
      icon: user
      link: "#what-we-do"

    - title: How we do it
      icon: user
      link: "#how-we-do-it"

    - title: Who we are
      icon: user
      link: "#who-we-are"

    - title: Imprint
      icon: user
      link: "#imprint"

    - title: Get in touch
      icon: user
      link: "#get-in-touch"
      is_big: true

  section1:
    title: What we do
    subtitle: Empower teams through coaching mentoring and tooling
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      buttonText: Get started
  section2:
    title: How we do it
    subtitle: People Product Process
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: Who we are
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  section4:
    title: Get in touch
    subtitle: Reach out
    image: illustrations/mockups/app-mockup.png
    post_target: /path/to/sns/endpoint
  section5:
    title: Imprint
    subtitle: Because its a legal thing
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    product:
    - text: Discover features
      link: /
    - text: Why choose our product?
      link: /
    - text: Compare features
      link: /
    - text: Our roadmap
      link: /
    - text: Request features
      link: /
    docs:
    - text: Get started
      link: /
    - text: User guides
      link: /
    - text: Admin guide
      link: /
    - text: Developers
      link: /
    blogroll:
    - text: Latest news
      link: /
    - text: Tech articles
      link: /
    - text: Video blog
      link: /